/**
 * GTLNAV worker — Docker deployment path.
 *
 * Called by build.js when detection picks `hostingKind === 'docker'`.
 * Responsibilities:
 *   1. Ensure a Dockerfile exists (generate from template if not).
 *   2. docker build → tagged image.
 *   3. Allocate an internal port and start the container with safe defaults.
 *   4. HTTP health check; if it never becomes healthy, fail and remove.
 *   5. Return enough metadata for build.js to upsert runtime_instances and
 *      register the proxy route.
 */
import path from "node:path";
import fs from "node:fs/promises";
import url from "node:url";

import { config } from "./config.js";
import {
  dockerAvailable,
  dockerBuild,
  dockerContainerId,
  dockerRemove,
  dockerStart,
  makeContainerName,
  makeImageTag,
} from "./docker.js";
import { allocatePort, releasePort } from "./port-allocator.js";
import { waitForHealthy } from "./health.js";

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TEMPLATE_DIR = path.join(__dirname, "templates");

async function readTemplate(name) {
  const p = path.join(TEMPLATE_DIR, name);
  return fs.readFile(p, "utf8");
}

function applyTemplate(content, vars) {
  return content.replace(/\$\{([A-Z_]+)\}/g, (_, key) => {
    if (Object.prototype.hasOwnProperty.call(vars, key)) {
      return String(vars[key]);
    }
    return "";
  });
}

async function ensureDockerfile({ repoRoot, detection, internalPort, logger }) {
  const existing = path.join(repoRoot, "Dockerfile");
  try {
    await fs.access(existing);
    logger.info("Using repo Dockerfile.", "docker");
    return { source: "repo", path: existing };
  } catch {
    /* not present */
  }

  const templateName =
    detection.dockerfileTemplate === "next-ssr"
      ? "Dockerfile.next.txt"
      : "Dockerfile.node.txt";
  const tpl = await readTemplate(templateName);
  const nodeVersion =
    (detection.nodeVersion ?? "")
      .toString()
      .replace(/[^0-9.]/g, "")
      .split(".")[0] || "20";
  const rendered = applyTemplate(tpl, {
    NODE_VERSION: `${nodeVersion}-alpine`,
    PORT: String(internalPort),
  });
  const target = path.join(repoRoot, "Dockerfile.gtlnav-autogen");
  await fs.writeFile(target, rendered, "utf8");

  // Promote the autogen file to "Dockerfile" so plain `docker build .` picks it up.
  const dockerfilePath = path.join(repoRoot, "Dockerfile");
  await fs.copyFile(target, dockerfilePath);

  logger.info(
    `Wrote autogenerated Dockerfile (${templateName}) — node ${nodeVersion}-alpine, PORT=${internalPort}.`,
    "docker",
  );
  return { source: detection.dockerfileTemplate, path: dockerfilePath };
}

/**
 * Run the full docker deploy path.
 *
 * @returns {Promise<{
 *   ok: true,
 *   imageTag: string,
 *   containerName: string,
 *   containerId: string | null,
 *   internalPort: number,
 *   dockerfileSource: string,
 *   healthStatus: 'healthy' | 'unhealthy' | 'starting',
 * } | {
 *   ok: false,
 *   stage: string,
 *   errorMessage: string,
 *   containerName?: string,
 *   internalPort?: number,
 * }>}
 */
export async function runDockerBuild({
  repoRoot,
  detection,
  slug,
  deploymentId,
  envPairs,
  logger,
}) {
  if (!(await dockerAvailable())) {
    return {
      ok: false,
      stage: "docker_preflight",
      errorMessage:
        "Docker is not available on this worker. Install Docker and set GTLNAV_WORKER_DOCKER_ENABLED=true.",
    };
  }

  // Allocate a port BEFORE building so the Dockerfile template can bake it in.
  let internalPort;
  try {
    internalPort = await allocatePort();
  } catch (err) {
    return {
      ok: false,
      stage: "port_allocate",
      errorMessage: err.message ?? "Port allocation failed.",
    };
  }
  logger.info(`Allocated internal port 127.0.0.1:${internalPort}.`, "docker");

  // Ensure a Dockerfile in the repo root.
  let dockerfileMeta;
  try {
    dockerfileMeta = await ensureDockerfile({
      repoRoot,
      detection,
      internalPort,
      logger,
    });
  } catch (err) {
    releasePort(internalPort);
    return {
      ok: false,
      stage: "dockerfile",
      errorMessage: `Could not provision Dockerfile: ${err.message}`,
      internalPort,
    };
  }

  const imageTag = makeImageTag(slug, deploymentId);
  logger.info(`Building image ${imageTag}…`, "docker");
  const buildRes = await dockerBuild({
    imageTag,
    contextDir: repoRoot,
    logger,
  });
  if (!buildRes.ok) {
    releasePort(internalPort);
    return {
      ok: false,
      stage: "docker_build",
      errorMessage: buildRes.timedOut
        ? "docker build timed out."
        : `docker build failed (exit ${buildRes.code}).`,
      internalPort,
    };
  }

  const containerName = makeContainerName(slug, deploymentId);

  // Pre-remove any stale container with the same name (e.g. retry after failure).
  await dockerRemove(containerName, logger).catch(() => {});

  logger.info(`Starting container ${containerName} on port ${internalPort}…`, "docker");
  const runRes = await dockerStart({
    imageTag,
    containerName,
    internalPort,
    envPairs,
    logger,
  });
  if (!runRes.ok) {
    releasePort(internalPort);
    return {
      ok: false,
      stage: "docker_run",
      errorMessage: runRes.timedOut
        ? "docker run timed out."
        : `docker run failed (exit ${runRes.code}). ${runRes.stderr?.slice?.(0, 400) ?? ""}`.trim(),
      containerName,
      internalPort,
    };
  }

  logger.info("Waiting for container to become healthy…", "health");
  const health = await waitForHealthy({
    port: internalPort,
    path: "/",
    totalTimeoutMs: config.healthTimeoutMs,
    logger,
  });

  if (!health.ok) {
    // Tear down the container to avoid leaks; keep the image for inspection.
    await dockerRemove(containerName, logger).catch(() => {});
    releasePort(internalPort);
    return {
      ok: false,
      stage: "health",
      errorMessage: `Container started but never became healthy: ${health.lastError ?? "unknown"}.`,
      containerName,
      internalPort,
    };
  }

  const containerId = await dockerContainerId(containerName);
  logger.success(
    `Container ${containerName} healthy (status ${health.status}).`,
    "health",
  );

  return {
    ok: true,
    imageTag,
    containerName,
    containerId,
    internalPort,
    dockerfileSource: dockerfileMeta.source,
    healthStatus: "healthy",
  };
}
