#!/usr/bin/env bash
# GTLNAV — Caddy route refresh.
#
# Pulls /api/proxy/route-config from the control plane, writes
# /etc/caddy/routes.conf, and reloads Caddy if the file changed.
#
# Run on a 30s timer (systemd timer, cron, or `watch`):
#
#   GTLNAV_APP_URL=https://app.gtlnav.app \
#   GTLNAV_PROXY_SECRET=secret \
#   bash refresh-routes.sh
#
# Environment:
#   GTLNAV_APP_URL          control plane base URL
#   GTLNAV_PROXY_SECRET     shared secret (matches the control plane env var)
#   CADDY_BIN               default: /usr/bin/caddy
#   CADDYFILE               default: /etc/caddy/Caddyfile
#   ROUTES_CONF             default: /etc/caddy/routes.conf
#
# Requires: bash, curl, jq.

set -euo pipefail

: "${GTLNAV_APP_URL:?GTLNAV_APP_URL is required}"
: "${GTLNAV_PROXY_SECRET:?GTLNAV_PROXY_SECRET is required}"
CADDY_BIN="${CADDY_BIN:-/usr/bin/caddy}"
CADDYFILE="${CADDYFILE:-/etc/caddy/Caddyfile}"
ROUTES_CONF="${ROUTES_CONF:-/etc/caddy/routes.conf}"

TMP_BODY=$(mktemp)
TMP_OUT=$(mktemp)
trap 'rm -f "$TMP_BODY" "$TMP_OUT"' EXIT

# 1. Pull route config.
HTTP_CODE=$(curl -sS -o "$TMP_BODY" -w "%{http_code}" \
  -H "x-gtlnav-proxy-secret: ${GTLNAV_PROXY_SECRET}" \
  -H "x-gtlnav-proxy-id: caddy-$(hostname)" \
  "${GTLNAV_APP_URL%/}/api/proxy/route-config")

if [[ "$HTTP_CODE" != "200" ]]; then
  echo "[gtlnav] route-config returned HTTP $HTTP_CODE; keeping previous routes.conf" >&2
  exit 1
fi

# 2. Render routes.conf from the JSON payload.
{
  echo "# Auto-generated by infra/caddy/refresh-routes.sh."
  echo "# Source: ${GTLNAV_APP_URL%/}/api/proxy/route-config"
  echo "# Last refresh: $(date -Iseconds)"
  echo ""
  jq -r '
    .routes[] |
    if .upstream_kind == "static" then
      "\(.hostname) {",
      "  tls { on_demand }",
      "  root * \(.serve_path)",
      "  file_server",
      "  try_files {path} {path}/ /index.html",
      "  encode zstd gzip",
      "}",
      ""
    elif .upstream_kind == "docker" then
      "\(.hostname) {",
      "  tls { on_demand }",
      "  reverse_proxy \(.upstream_target) {",
      "    health_uri /",
      "    health_interval 10s",
      "    health_timeout 4s",
      "  }",
      "  encode zstd gzip",
      "}",
      ""
    else
      empty
    end
  ' "$TMP_BODY" >"$TMP_OUT"
} || {
  echo "[gtlnav] failed to render routes.conf" >&2
  exit 1
}

# 3. Atomic swap + reload only when content changed.
if ! diff -q "$TMP_OUT" "$ROUTES_CONF" >/dev/null 2>&1; then
  install -m 0644 "$TMP_OUT" "$ROUTES_CONF"
  if [[ -x "$CADDY_BIN" ]]; then
    "$CADDY_BIN" reload --config "$CADDYFILE" >/dev/null
    echo "[gtlnav] routes.conf updated; caddy reloaded."
  else
    echo "[gtlnav] routes.conf updated; caddy reload skipped (CADDY_BIN missing)."
  fi
else
  echo "[gtlnav] routes.conf unchanged."
fi
