#!/usr/bin/env bash
# GTLNAV — install Caddy v2 on Ubuntu 22.04 / 24.04 LTS.
#
# Idempotent. Re-running on a host that already has Caddy is a no-op.
#
# Run as root (or with sudo):
#   sudo bash infra/setup/install-caddy.sh
#
# Side effects:
#   1. Installs the official `caddy` package from cloudsmith.
#   2. Creates /etc/caddy/{Caddyfile,routes.conf} as empty placeholders.
#      (The real Caddyfile is shipped by infra/caddy/Caddyfile.example —
#       this script does NOT overwrite an existing file.)
#   3. Enables + starts the caddy systemd unit.
#   4. Installs jq + curl (required by refresh-routes.sh).

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "[gtlnav] install-caddy.sh must run as root (use sudo)." >&2
  exit 1
fi

if command -v caddy >/dev/null 2>&1; then
  CURRENT="$(caddy version 2>/dev/null || true)"
  echo "[gtlnav] Caddy already installed: ${CURRENT}"
else
  echo "[gtlnav] Installing prerequisites…"
  apt-get update -y
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl gnupg jq

  echo "[gtlnav] Adding Caddy APT repo…"
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
    | gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
    | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null

  echo "[gtlnav] Installing Caddy…"
  apt-get update -y
  apt-get install -y caddy
fi

# jq is required by refresh-routes.sh — install it even if Caddy was present.
if ! command -v jq >/dev/null 2>&1; then
  apt-get install -y jq curl
fi

echo "[gtlnav] Ensuring /etc/caddy/{Caddyfile,routes.conf} exist…"
mkdir -p /etc/caddy
if [[ ! -f /etc/caddy/Caddyfile ]]; then
  cat >/etc/caddy/Caddyfile <<'EOF'
# Placeholder Caddyfile created by install-caddy.sh.
# Replace with infra/caddy/Caddyfile.example, edit the apex domain + emails,
# then `systemctl reload caddy`.
{
  email ops@example.com
}
EOF
fi
if [[ ! -f /etc/caddy/routes.conf ]]; then
  echo "# Auto-generated by infra/caddy/refresh-routes.sh — do not edit by hand." \
    >/etc/caddy/routes.conf
fi
chmod 0644 /etc/caddy/Caddyfile /etc/caddy/routes.conf

systemctl enable --now caddy

if systemctl is-active --quiet caddy; then
  echo "[gtlnav] Caddy is running. Version: $(caddy version | head -n1)"
else
  echo "[gtlnav] WARN — caddy did not start cleanly. Check 'journalctl -u caddy'." >&2
fi
